name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Generate wrapper
        run: gradle wrapper

      - name: Commit wrapper
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Add Gradle wrapper" || echo "No changes"
          git push
