#!/usr/bin/env sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running on CI: this script must remain exactly as generated.
#
##############################################################################

# Attempt to set APP_HOME
APP_HOME=$(cd "${0%/*}" && pwd -P)

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD" = "maximum" ] ; then
    MAX_FD=$(ulimit -H -n) || MAX_FD=
fi

if [ -n "$MAX_FD" ] ; then
    ulimit -n "$MAX_FD" >/dev/null 2>&1 || true
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" $DEFAULT_JVM_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
